version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
    groups:
      python-runtime-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "pytest*"
          - "ruff"
      python-dev-deps:
        patterns:
          - "pytest*"
          - "ruff"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(actions)"
